sudo : required
services:
  - docker
before_install :
   - docker build -t mmuretimartin/docker-react -f Dockerfile.dev .

script:
   - docker run mmuretimartin/docker-react npm run test -- --coverage --watchAll=false
deploy:
   provider: elasticbeanstalk 
   region: "us-east-1"
   app: "docker"
   env: "Docker-env"
   bucket_name: "elasticbeanstalk-us-east-1-894185464211"
   bucket_path: "docker."
   on:
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY

      
